### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by mrlacey**
Just a few quick typo fixes - found when first reading through.

### CODE REVIEW

**Comment by SavoySchuler** [comment]
Thanks for watching my back, @mrlacey!

**Comment by SavoySchuler** [comment]
I had the targets confused, I thought this was for NumberBox and now see its for Rounded Corners. Either way, thank you for your vigilance, @mrlacey! Awesome you caught these and submitted a PR for them!

**Comment by mrlacey** [comment]
@SavoySchuler with the NumberBox proposal there were already so many comments on that one PR I didn't want to complicate things by spreading feedback over multiple locations. Also, a lot of the things I was calling out on the NumebrBox spec were things where there was evidence of external thought and reasoning that hadn't yet made it into the spec but I just wanted to make sure they were noted and so could be added in when appropriate, rather than adding my own assumptions for the decisions that had been made,

**Comment by SavoySchuler** [comment]
Oh, no worries, @mrlacey! Your contributions are perfect! I had accidentally merged this on behalf of @chigy and was adding a note for her and a "thank you" to you while I was in here. Sorry - I could have been more clear!

**Pull request merged**
